/* Generated by printed-curtain-render. Edit and reload to refine the lockup. */
var CURTAIN_ARTWORK = {
  "id": "vibe-motion",
  "name": "VIBE MOTION",
  "artboard": {
    "w": 1200,
    "h": 1600,
    "lockup": 180,
    "anchor": 790.0
  },
  "images": [],
  "lines": [
    {
      "text": "VIBE MOTION",
      "family": "\"Helvetica Neue\", Arial, sans-serif",
      "weight": "700 ",
      "cx": 600.0,
      "y": 700,
      "h": 180,
      "w": 920
    }
  ]
};

var CURTAIN_STYLE = {
  "cloth": [
    210,
    200,
    186
  ],
  "ink": [
    42,
    33,
    29
  ],
  "backdrop": [
    235,
    229,
    219
  ]
};
